version: 2
jobs:
  test-golang:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yonkornilov/snowcapper
    steps:
      - checkout
      - run: make get
      - run: make test
  
workflows:
  version: 2
  btd:
    jobs:
      - test-golang
