version: 2
jobs:
  test-golang:
    docker:
      - image: golang:1.9-alpine3.8
    working_directory: /go/src/github.com/yonkornilov/cloudless-init
    steps:
      - checkout
      - run: apk update 
      - run: apk add make gcc
      - run: make get 
      - run: make test 
  
workflows:
  version: 2
  btd:
    jobs:
      - test-golang
