version: 2
jobs:
  test-golang:
    docker:
      - image: golang:1.9-alpine3.8
    working_directory: /go/src/github.com/yonkornilov/cloudless-init
    steps:
      - checkout
      - run: apk update 
      - run: apk add make gcc g++
      - run: make get 
      - run: make test 
  build:
    docker:
      - image: golang:1.9-alpine3.8
    working_directory: /go/src/github.com/yonkornilov/cloudless-init
    steps:
      - checkout
      - run: apk update 
      - run: apk add make gcc g++
      - run: make get 
      - run: make plugin 
      - persist_to_workspace:
          root: /go/src/github.com/yonkornilov/cloudless-init
          paths:
            - cloudless-init.so 
  deploy:
    docker:
      - image: tsub/ghr 
    working_directory: /
    steps:
      - attach_workspace:
          at: /
      - run: ghr $CIRCLE_TAG cloudless-init.so
workflows:
  version: 2
  btd:
    jobs:
      - test-golang
      - build:
          requires:
            - test-golang
      - deploy:
          filters:
            branches:
              ignore: /.*/
	    tags:
	      only: /^v.*/
          requires:
            - build 
