version: 2
jobs:
  test-golang:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yonkornilov/cloudless-init
    steps:
      - checkout
      - run: go get -pkgdir _/tmp -buildmode=plugin ./...
      - run: go test -pkgdir _/tmp -buildmode=plugin ./...
  
workflows:
  version: 2
  btd:
    jobs:
      - test-golang
